### PR TITLE
fix ⚡️: Rewrite the history

### PR DESCRIPTION
**Pull request by melMass**
This is an attempt at fixing [a767fb98](https://github.com/IntegroLabs/hicetnunc/commit/a767fb98) that introduced a 92.8mb  wav file in the history

image

### CODE REVIEW

**Comment by melMass** [comment]
This needs to be reviewed, it's a draft PR, I just can't find the switch icon 😅 !

**Comment by melMass** [comment]
This will likely break @nftbiker 's PR so I might have to do it after this is merged.
@jmagly do you know when #14 is mergeable?

**Comment by xat** [comment]
Before:
Bildschirmfoto 2022-02-04 um 08 10 41

After:
Bildschirmfoto 2022-02-04 um 08 11 28

**Comment by xat** [comment]
@melMass what git commands did you use to remove that file? at first glance, the pr looks good to me.

**Comment by melMass** [comment]
Interesting `du -hs` returns 72m for me. It's still too much imo 😆 ✂️ 

> what git commands did you use to remove that file?

At first `git filter` but it was slow and messy, I ended up using [bfg](https://rtyley.github.io/bfg-repo-cleaner/)
`bfg --strip-blobs-bigger-than 90M`

**Comment by melMass** [comment]
@xat Actually..... 😅 

image

**Comment by xat** [comment]
looks good and can be merged, imo! :-)

just as a tip: it's usually nicer to rebase a feature branch on-top of the main branch, instead of merging the changes from main into the feature branch. that way you get cleaner git history. but no need to change in this case :-)

**Comment by melMass** [comment]
> looks good and can be merged, imo! :-)
> 
> just as a tip: it's usually nicer to rebase a feature branch on-top of the main branch, instead of merging the changes from main into the feature branch. that way you get cleaner git history. but no need to change in this case :-)

Definitely I should have thought of this before, I can try a rebase but with all the edits I might mess things up  😬

**Comment by xat** [comment]
yeah, it's not worth changing now.

**Comment by melMass** [comment]
Ok re-starting this from scratch on top on NFTBiker's PR, now I know what to look for

**Pull request closed without merging**
